Cargo.toml

Bumps the version number so we can update the README and metadata on crates.io/docs.rs.

Prepare 0.24.1

---

README.md

The links and commands to run the examples were out of date, so I've updated them.
Replaces #5, which doesn't change the commands.

docs: fix examples section of README

---

Cargo.toml

While investing something else in nats.rs library, after running
```
cargo +nightly update -Zminimal-versions
cargo check  --all-targets
```
I found some errors in this repo minimum versions. 
This bumps them to the required minimum.
Signed-off-by: Tomasz Pietrek <melgaer@gmail.com>

Fix minimal dependency versions

---

src/lib.rs

As `tokio-rustls` is a crate for collaborating `tokio` and `rustls`, it might be more simple to use `tokio::pin` than `futures_util::pin_mut` in the document.

Replace futures_util::pin_mut with tokio::pin in doc

---

Cargo.toml

I depend both upon tokio-rustls as well as rustls.
I cannot update either of the dependencies without them both being in sync.
This PR fixes that, which should allow me to upgrade to the latest alpha version of rustls once again.
It's my first contribution to your organisation or repository, so please do let me know in case I forgot some pre-requirements or missed some process details. If so, my appologies.

update rustls dependency to alpha.6

---

.gitignore
Cargo.toml
examples/client.rs
examples/server.rs
tests/badssl.rs
tests/early-data.rs
tests/test.rs
tests/utils.rs

This branch updates to rustls 0.22 and bumps the crate version from 0.25.0-alpha.4 to 0.25, taking the following associated updates:
* rustls 0.22.0-alpha-4 -> 0.22
* pki-types 0.2.2 -> 1
* webpki-roots 0.26.0-alpha.2 -> 0.26
* rustls-pemfile 2.0.0-alpha.2 -> 2
* webpki 0.102.0-alpha.8 -> 0.102
Breaking API changes are addressed as required.

Prepare 0.25 release, update to Rustls 0.22

---

README.md

The example code in the README under "Basic Structure of a Client" does not work with the latest version of the library.  This PR updates it for v0.25.0.

Update example code in README for v0.25.0

---

Cargo.toml
src/common/handshake.rs
src/common/mod.rs
src/lib.rs
tests/test.rs

- Track new alert-sending API for Acceptor.
nb. I have quite little experience in this codebase and not much confidence with async generally, so please give this a detailed look.

Take rustls 0.23

---

src/common/mod.rs

Ignore NotConnected error in poll_shutdown()

---

Cargo.toml

This avoids people having to add `rustls` directly to their Cargo.toml just to enable a feature.

feat: add fips pass-through feature

---

src/common/handshake.rs

Identified by comparing the implementation of https://github.com/rustls/futures-rustls/pull/9 to https://github.com/rustls/tokio-rustls/pull/44. Previous to this PR, we do not necessarily poll the alert.write to completion

fix: check for ErrorKind::WouldBlock in MidHandshake::SendAlert poll

---

.github/workflows/CI.yml
Cargo.toml

It would be confusing for rustls docs to say "by default it uses [aws-lc-rs](https://crates.io/crates/aws-lc-rs) for implementing the cryptography in TLS" but discover that tokio-rustls changes the default.

feat: change default crypto provider to match rustls'

---

src/lib.rs
tests/test.rs

Fix: Check for ErrorKind::WouldBlock in LazyConfigAcceptor

---

examples/client.rs
examples/server.rs

Addresses an issue I encountered trying to use the client and server examples in standalone projects:
>the trait `From<Arc<rustls::ServerConfig>>` is not implemented for `TlsAcceptor`
>the trait `From<Arc<rustls::ClientConfig>>` is not implemented for `TlsConnector`
These modifications ensure that the code uses `rustls` types re-exported by `tokio-rustls` when compiled in a context outside of the library.

Ensure examples use re-exported rustls types outside of the tokio-rustls context

---

src/client.rs
src/common/mod.rs
src/common/test_stream.rs
src/lib.rs
src/server.rs
tests/badssl.rs
tests/early-data.rs
tests/utils.rs

Allows making use of https://github.com/rustls/rustls/pull/1640.
Supersedes #25
I've also run tests with #44 and it seems to work correctly.
Closes #25
Closes #26

Forward vectored writes

---

Cargo.toml

Preparation to cut a new 0.26.0 release to bring in [changes since 0.25](https://github.com/rustls/tokio-rustls/compare/534344388ecc6634a133bd619c49170a79e38dc8..56653423810ff032a9505b6902e0ac1d6927e448).
This repo doesn't have an established CHANGELOG or GitHub releases, but the major callouts I would include would be:
* Support for Rustls 0.23 and the new acceptor alert API - by @ctz in #44
* Support for aws-lc-rs as the new default crypto backend, allowing passthrough of the `fips` feature - by @BiagioFesta in #43, @jbr in #49, #50
* Support for forwarding vectored writes - by @paolobarbolini in #45
* Ignoring `NotConnected` error in `poll_shutdown` - by @djc in #42
* Check for `ErrorKind::WouldBlock` in `MidHandshake::SendAlert` poll - by @jbr in #47
* Check for …

Cargo: 0.25.0 -> 0.26.0

---

src/common/mod.rs
src/common/test_stream.rs

A weekly CI run noticed a change from `io::Error::UnexpectedEof` to `InvalidData` today in a [test](https://github.com/rustls/tokio-rustls/blob/main/src/common/test_stream.rs#L257) for https://github.com/tokio-rs/tls/issues/77 (that should likely have triggered me to follow-up directly in rustls itself back in the day...), which was fixed in https://github.com/tokio-rs/tls/pull/78. I also added a commit to remove the extra logic which now appears to be unnecessary.
It makes sense to me that `InvalidData` is probably a better error for this than `UnexpectedEof`.
Fixes #67.

Fix test regression after rustls improvements in complete_io()

---

examples/server.rs

Using [`rustls_pemfile::rsa_private_keys`](https://docs.rs/rustls-pemfile/latest/rustls_pemfile/fn.rsa_private_keys.html) is overly specific, limiting use to just RSA keys with PKCS#1 encoding.
This commit switches to using [`rustls_pemfile::private_key`](https://docs.rs/rustls-pemfile/latest/rustls_pemfile/fn.private_key.html) which is tailor made for loading one private key in any of the supported formats.
Updates https://github.com/rustls/tokio-rustls/issues/76

examples: prefer pemfile::private_key

---

examples/client.rs
src/common/mod.rs
src/common/test_stream.rs
tests/utils.rs

Applies the result of `clippy --fix`.

proj: fix clippy 1.83 findings

---

Cargo.lock
Cargo.toml

We seem to have [updated MSRV](https://github.com/rustls/tokio-rustls/commit/409d8742efd3f2b2976623edfe80e0b5dc57769f), I'm not sure about our MSRV policy, do we need to release 0.27.0? cc @djc

release 0.26.1

---

.github/workflows/CI.yml

We already do this in most of the other Rustls crates, and Zizmor 0.7.0 [flags its absence](https://woodruffw.github.io/zizmor/audits/#artipacked) in this repo. As mentioned in the description of this finding:
> By default, using [actions/checkout](https://github.com/actions/checkout) causes a credential to be persisted in the checked-out repo's .git/config, so that subsequent git operations can be authenticated.
> 
> Subsequent steps may accidentally publicly persist .git/config, e.g. by including it in a publicly accessible artifact via [actions/upload-artifact](https://github.com/actions/upload-artifact).
>
> However, even without this, persisting the credential in the .git/config is non-ideal unless actually needed.
We don't need it, so turn it off :-)

ci: use persist-credentials: false throughout

---

.github/workflows/CI.yml
Cargo.toml

The upstream Rustls library updated its MSRV to 1.71 for 0.23.20+
Ref. https://github.com/rustls/rustls/pull/2220, https://github.com/rustls/rustls/issues/2239#issuecomment-2498638066

Cargo: MSRV 1.70 -> 1.71

---

Cargo.lock
Cargo.toml
src/client.rs
src/common/mod.rs
src/common/test_stream.rs
src/lib.rs
src/server.rs
tests/test.rs

Now that https://github.com/rustls/rustls/pull/2303 is merged, we can make use of it to implement AsyncBufRead.
This also reimplements AsyncRead in terms of AsyncBufRead, which indirectly fixes #55.

Implement AsyncBufRead

---

src/lib.rs

This patch exposes underlying `ClientConfig` and `ServerConfig` for `TlsConnector` and `TlsAcceptor`. My use-case is I'm use `TlsConnector` as API but I have to check if it's correctly configured.

feat: add access to underlying config

---

.gitignore
README.md

When I was trying to test out the server example, at first I was thrown off because `README.md` mentioned `.der` files (a binary format). After looking at the code again, it turned out the solution was to use `.pem` files instead (text format). To make it easier, I've also included instructions for how to create certificate and key pem files with `openssl` commands.

Clarify how to run the example server

---

src/client.rs
src/common/handshake.rs
src/common/mod.rs
src/lib.rs
src/server.rs
tests/early-data.rs
tests/test.rs
tests/utils.rs

@almindor pointed out a potential issue with poll_flush within handshake. If write returns Ready, but flush returns Pending, it's guaranteed that the `handshake()` function returns and loses the `need_flush` state. If there's no more data to write, then it will never attempt to flush or write again.
Given the nature of TLS, it could be the client hello still needs flushing before a server hello would ever be readable.
This normally wouldn't be observable against a TcpStream, given that TcpStream has no flush impl.
The first commit creates a test that currently times out. The second commit introduces a potential fix which caches the `need_flush` state. ~~I'm not sure what to do about early-data handling.~~

fix: handshake does not fully flush writes

---

src/server.rs

This adds two methods to the existing `StartHandshake` in order to allow splitting and reconstructing the underlying components.
For context and usecase, see https://github.com/rustls/tokio-rustls/issues/125.

server: allow splitting and reassembling a `StartHandshake`

---

.github/workflows/CI.yml
Cargo.lock
Cargo.toml

PR for the issue #131.
The changes require bumping minimal rust version to `1.75` (a build requirement of the `zlib-rs` crate).

Add TLS certificate compression features
